### ISSUE TITLE
funcionamiento del los enemigos con veneno

### ISSUE THREAD

**Issue by RDHLaura** [RDHLaura/RingOfPain#3]
No sé si estos también activan a los venenosos cercanos o solo los contamina

**Comment by pn3m0n1c** [comment]
En principio el veneno es individual. Depende de si meten un objeto que cause un efecto de veneno en área. Lo suyo sería crearla de manera que si queremos extenderla a otras cartas se pueda hacer fácil, en plan enemigo.venenoArea (e infecta a los que estén a su izquierda y su derecha)
